# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               MolecularCloud.it
tagline:             Angelo Varlotta's Blog
url:                 http://molecularcloud.it
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Angelo Varlotta
  url:               https://twitter.com/varlottaang
  email:             angvarlotta@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/varlottaang/varlottaang.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
